version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download

builds:
  - id: jx-release-version
    # Path to main.go file or main package.
    # Default is `.`.
    main: ./main.go

    # Binary name.
    # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
    # Default is the name of the project directory.
    binary: jx-release-version

    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -X "main.Version={{.Env.VERSION}}" -X "main.Revision={{.Env.REV}}" -X "main.Date={{.Env.BUILDDATE}}"

    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are darwin and linux.
    goos:
      - windows
      - darwin
      - linux

    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are 386 and amd64.
    goarch:
      - amd64
      - arm
      - arm64

archives:
  - name_template: "jx-release-version-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  # You can change the name of the checksums file.
  # Default is `jx-cli_{{ .Version }}_checksums.txt`.
  name_template: "jx-release-version-checksums.txt"

  # Algorithm to be used.
  # Accepted options are sha256, sha512, sha1, crc32, md5, sha224 and sha384.
  # Default is sha256.
  algorithm: sha256

release:
  # You can change the name of the GitHub release.
  # Default is `{{.Tag}}`
  name_template: "{{.Env.VERSION}}"

sboms:
  - artifacts: archive
